version: 1.0.{build}
image: Visual Studio 2017
before_build:
 - appveyor-retry dotnet restore -v Minimal
build:
  verbosity: minimal
on_success:
- curl -s -o upload https://copilot.blackducksoftware.com/ci/appveyor/scripts/upload
- bash <(curl -s -L https://github.com/whitesource/fs-agent-distribution/raw/master/standAlone/wss_agent.sh) -apiKey 41c71f81b00e4ec5868fece050113260fa23031c6fac460a81945a99bfaeea51 -product mytest -project example-nuget-appveyor -d . 
- curl -s https://scripts.scantist.com/staging/scantist-bom-detect.jar --output scantist-bom-detect.jar
- java -jar scantist-bom-detect.jar
